[package]
name = "main"
version = "1.0.0"
edition = "2021"

[dependencies]
sbor = { version = "1.3.0" }
scrypto = { version = "1.3.0" }
radix-common = { version = "1.3.0" }
curve-calcs-interface = { path = "../../libraries/curve-calcs-interface"}
curve-cs2-v1 = { path = "../curve-cs2-v1" }
dex-interface = { path = "../../libraries/dex-interface"}

[dev-dependencies]
scrypto-test = { version = "1.3.0" }
main = { path = ".", features = ["test"] }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
