[package]
name = "dex-ociswap-v2"
version = "0.1.0"
edition = "2021"
description = "Defines the dex adaptor for ociswap flex pools v2"

[dependencies]
sbor = { version = "1.3.0" }
scrypto = { version = "1.3.0" }
radix-common = { version = "1.3.0" }
scrypto-interface = { path = "../../libraries/scrypto-interface" }
dex-interface = { path = "../../libraries/dex-interface" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
